// =====================================
// EduNexus Report Generator
// Mouse Innovations
// =====================================


function generateReport(){


try{


const { jsPDF } = window.jspdf;


const pdf = new jsPDF();



// STUDENT PROFILE NAME

let savedUser =
JSON.parse(
localStorage.getItem("edunexus_google_user")
||
"{}"
);


let student =
savedUser.name
||
savedUser.email
||
"EduNexus Student";



// DATE

let date =
new Date()
.toLocaleString();



// GET RESULT SAFELY

let score =
document.body.innerText.match(/Score:\s*(\d+)/);


score =
score ? score[1] : "N/A";



// CONNECTION METHOD
// Power Converter/Bridge Rectifier experiments run through either
// pcState (assessment.js) or expState (experiment.js) depending on
// which screen the student is on. Both expose .mode as "manual" or
// "hardware". Fall back to "Not specified" if neither is present so
// the report never silently prints wrong info.

let connMode =
(typeof pcState !== "undefined" && pcState && pcState.mode) ||
(typeof expState !== "undefined" && expState && expState.mode) ||
null;

let connectionMethod =
connMode === "hardware"
? "Hardware Kit"
: connMode === "manual"
? "Manual Connection"
: "Not specified";



// TITLE

pdf.setFontSize(18);


pdf.text(
"EduNexus Virtual Laboratory Report",
20,
20
);



pdf.setFontSize(11);


pdf.text(
"Mouse Innovations - AI Digital Twin Laboratory",
20,
30
);



pdf.line(
20,
35,
190,
35
);




// DETAILS


pdf.setFontSize(12);



pdf.text(
"Student Name : "+student,
20,
50
);



pdf.text(
"Experiment : Power Converter Digital Twin",
20,
60
);



pdf.text(
"Date : "+date,
20,
70
);



pdf.text(
"Connection Method : "+connectionMethod,
20,
80
);




// AIM


pdf.setFontSize(14);


pdf.text(
"AIM:",
20,
100
);


pdf.setFontSize(11);


pdf.text(
"To perform power electronics experiment -BRIDGE RECTIFIER",
20,
110
);


pdf.text(
"using AI based virtual laboratory.",
20,
118
);




// PROCEDURE


pdf.setFontSize(14);


pdf.text(
"PROCEDURE:",
20,
140
);


pdf.setFontSize(11);



pdf.text(
"1. Login to EduNexus platform",
20,
150
);


pdf.text(
"2. Study theory using AI Tutor",
20,
158
);


pdf.text(
"3. Perform Digital Twin experiment",
20,
166
);


pdf.text(
"4. Submit assessment",
20,
174
);




// OBSERVATION


pdf.setFontSize(14);


pdf.text(
"OBSERVATION:",
20,
195
);


pdf.setFontSize(11);



pdf.text(
"Score : "+score+" %",
20,
205
);




// RESULT


pdf.setFontSize(14);


pdf.text(
"RESULT:",
20,
225
);



pdf.setFontSize(11);


pdf.text(
"Experiment completed and evaluated successfully.",
20,
235
);



// FOOTER


pdf.setFontSize(10);



pdf.text(
"Generated by EduNexus X - Mouse Innovations",
20,
290
);



// PREVIEW PDF + DOWNLOAD OPTION


const pdfURL =
pdf.output(
"bloburl"
);


window.open(
pdfURL,
"_blank"
);


}


catch(error){


console.log(error);


alert(
"Report generation error. Check console."
);


}



}