"""
Per-student Level 2 target resistance generator.

Each student who opens the Target Resistance Challenge gets their OWN
randomly generated target — not the same number as everyone else — so
students can't just pass answers around. The target is deterministically
seeded from (assessment_id, user_id), so it's stable across reloads/retries
for that student, but different from every other student's target.

Values are generated by combining 2-4 of the REAL resistors that exist on
the physical Resistance Bank board (mirrors RB_PAIRS in frontend/assessment.js
exactly) in series/parallel, so every generated target is actually buildable
on the hardware — not an arbitrary unreachable number.
"""

import hashlib
import random

# Must stay in sync with RB_PAIRS in frontend/assessment.js.
# (socket_a, socket_b, silkscreen_label, ohms)
BOARD_RESISTORS = [
    ("1", "2", "1K", 1000), ("7", "8", "47R", 47), ("15", "16", "4K7", 4700),
    ("21", "22", "3K3", 3300), ("9", "10", "6K7", 6700), ("17", "18", "70R", 70),
    ("23", "24", "68K", 68000), ("3", "4", "22R", 22), ("11", "12", "680R", 680),
    ("25", "26", "100R", 100), ("27", "28", "33K", 33000), ("5", "6", "470R", 470),
    ("13", "14", "2K2", 2200), ("19", "20", "680R", 680), ("29", "30", "100R", 100),
]

_OHM_VALUES = [r[3] for r in BOARD_RESISTORS]


def _seed_for(assessment_id: int, user_id: int) -> random.Random:
    """Deterministic per-(assessment, student) seed so the same student
    always regenerates the same target, but different students get
    different targets."""
    h = hashlib.sha256(f"l2-target:{assessment_id}:{user_id}".encode()).hexdigest()
    return random.Random(int(h[:16], 16))


def _combine(values, mode: str) -> float:
    if mode == "series":
        return sum(values)
    # parallel
    inv = sum(1.0 / v for v in values if v > 0)
    return 1.0 / inv if inv > 0 else 0.0


def generate_target_ohms(assessment_id: int, user_id: int,
                          min_ohms: float = None, max_ohms: float = None,
                          max_tries: int = 200) -> float:
    """Generate a realistic, board-achievable target resistance for one
    student, using 2-4 real board resistors combined in series/parallel,
    optionally constrained to [min_ohms, max_ohms] set by staff."""
    rng = _seed_for(assessment_id, user_id)

    best_value = None
    for _ in range(max_tries):
        k = rng.choice([2, 2, 3, 3, 4])  # bias toward simpler 2-3 resistor combos
        picks = rng.sample(_OHM_VALUES, k=min(k, len(_OHM_VALUES)))
        mode = rng.choice(["series", "parallel", "series", "parallel", "mixed"])

        if mode == "mixed" and len(picks) >= 3:
            # (R1 + R2) parallel with R3 [parallel with R4 if present]
            split = len(picks) // 2
            group_a = _combine(picks[:split], "series")
            group_b = _combine(picks[split:], "series")
            value = _combine([group_a, group_b], "parallel")
        else:
            value = _combine(picks, "series" if mode == "series" else "parallel")

        if value <= 0 or value != value:  # skip zero / NaN
            continue

        if min_ohms is not None and value < min_ohms:
            continue
        if max_ohms is not None and value > max_ohms:
            continue

        return round(value, 2)

    # Fallback: no combo landed inside the staff's range within max_tries —
    # return the closest valid combo found instead of failing outright.
    if best_value is not None:
        return round(best_value, 2)
    # Absolute last resort: single resistor closest to the midpoint of range.
    mid = ((min_ohms or 1) + (max_ohms or 100000)) / 2
    closest = min(_OHM_VALUES, key=lambda v: abs(v - mid))
    return float(closest)
